Improve data processing (#40)

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -39,6 +39,17 @@ jobs:
         run: |
           poetry install
 
+      - name: Run Example tests
+        run: |
+          poetry run .github/test_vast.py configs/examples/growth_sim/growth_sim.vast -c test-1-1
+
+      - name: Check postprocessed file for growth_sim
+        run: |
+          if [ ! -f "results/.postprocessed" ]; then
+            echo "✗ .postprocessed file not found for growth_sim.vast"
+            exit 1
+          fi
+
       - name: Run CLI tests
         run: |
           bash .github/test_commands.sh
