fix test

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -47,6 +47,15 @@ jobs:
         run: |
           poetry run .github/test_vast.py configs/examples/growth_sim/growth_sim.vast -c test-1-1
 
+      - name: Check postprocessed file for growth_sim
+        run: |
+          find results -type f
+
+          if [ ! -f "results/.postprocessed" ]; then
+            echo "✗ .postprocessed file not found for growth_sim.vast"
+            exit 1
+          fi
+
       - name: Run Example tests
         run: |
           poetry run .github/test_vast.py configs/examples/basic_nav/basic_nav.vast -c test-1
